name: Build & test services

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-front-end:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
    - run: cd ./dj-collab-vue

    - run: npm install
    - run: npm test