name: Build & test services

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-front-end:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dj-collab-vue
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: dj-collab-vue

    - run: npm install
    - run: npm run-script build