name: Docker Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dj-collab-vue

    steps:
      - uses: actions/checkout@v3
    
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: sioravw/dj-collab
              
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dj-collab-vue/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}